const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
    NEW_WAITING: "NEW_WAITING",
    WAITING_ROOM_MEMBERS: "WAITING_ROOM_MEMBERS",
    CONNECT_ME: "CONNECT_ME",
    MY_USERNAME: "MY_USERNAME",
    DISCONNECT: "DISCONNECT",
    REQUEST_JOIN: "REQUEST_JOIN",
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    JOINED_WAITING_ROOM: "JOINED_WAITING_ROOM",
    CONNECTEDWITHYOU: "CONNECTEDWITHYOU",
    CONNECTED: "CONNECTED",
    OTHER_USERNAME: "OTHER_USERNAME",
    DISCONNECTED: "DISCONNECTED",
    LEFT_YOU: "LEFT_YOU",
    REQUEST_JOIN_RESPONSE: "REQUEST_JOIN_RESPONSE",
  },
};
export default EVENTS;
